import path from 'path'
import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import fs from 'fs'

const manifest = JSON.parse(fs.readFileSync('manifest.json', 'utf8'))

const nodeBuiltins = [...builtins, ...builtins.map((mod) => `node:${mod}`)]

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    '@lexical/clipboard/clipboard',
    ...nodeBuiltins,
  ],
  format: 'cjs',
  inject: [path.resolve('import-meta-url-shim.js')],
  // node-fetch 2.x imports whatwg-url only as `Url.URL || whatwgUrl.URL`, and
  // Electron's Node always has `url.URL`; the shim drops ~280KB (whatwg-url +
  // tr46) that can never execute. Host bundle only — tests and runtime
  // components resolve the real package.
  alias: {
    'whatwg-url': path.resolve('whatwg-url-shim.js'),
  },
  define: {
    'import.meta.url': 'import_meta_url',
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
    '__PLUGIN_BAKED_VERSION__': JSON.stringify(manifest.version),
  },
  target: 'es2020',
  // Obsidian loads the plugin as CommonJS. Desktop SDKs use dynamic imports
  // for Node builtins; leaving those as native `import()` makes Chromium try
  // to fetch specifiers such as `node:os`. Lower them to async `require()`.
  supported: {
    'dynamic-import': false,
  },
  logLevel: 'info', // 'debug' for more detailed output
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  metafile: true,
  loader: {
    '.svg': 'dataurl',
    '.md': 'text',
  },
  plugins: [],
})

if (prod) {
  const result = await context.rebuild()
  fs.writeFileSync('meta.json', JSON.stringify(result.metafile))
  process.exit(0)
} else {
  await context.watch()
}
